/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as RegisterIndexImport } from './routes/register/index'
import { Route as LoginIndexImport } from './routes/login/index'
import { Route as ExerciciosIndexImport } from './routes/exercicios/index'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as ExerciciosCategoriaExercicioImport } from './routes/exercicios/$categoriaExercicio'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RegisterIndexRoute = RegisterIndexImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRoute,
} as any)

const LoginIndexRoute = LoginIndexImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const ExerciciosIndexRoute = ExerciciosIndexImport.update({
  id: '/exercicios/',
  path: '/exercicios/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRoute,
} as any)

const ExerciciosCategoriaExercicioRoute =
  ExerciciosCategoriaExercicioImport.update({
    id: '/exercicios/$categoriaExercicio',
    path: '/exercicios/$categoriaExercicio',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/exercicios/$categoriaExercicio': {
      id: '/exercicios/$categoriaExercicio'
      path: '/exercicios/$categoriaExercicio'
      fullPath: '/exercicios/$categoriaExercicio'
      preLoaderRoute: typeof ExerciciosCategoriaExercicioImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof rootRoute
    }
    '/exercicios/': {
      id: '/exercicios/'
      path: '/exercicios'
      fullPath: '/exercicios'
      preLoaderRoute: typeof ExerciciosIndexImport
      parentRoute: typeof rootRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exercicios/$categoriaExercicio': typeof ExerciciosCategoriaExercicioRoute
  '/dashboard': typeof DashboardIndexRoute
  '/exercicios': typeof ExerciciosIndexRoute
  '/login': typeof LoginIndexRoute
  '/register': typeof RegisterIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exercicios/$categoriaExercicio': typeof ExerciciosCategoriaExercicioRoute
  '/dashboard': typeof DashboardIndexRoute
  '/exercicios': typeof ExerciciosIndexRoute
  '/login': typeof LoginIndexRoute
  '/register': typeof RegisterIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/exercicios/$categoriaExercicio': typeof ExerciciosCategoriaExercicioRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/exercicios/': typeof ExerciciosIndexRoute
  '/login/': typeof LoginIndexRoute
  '/register/': typeof RegisterIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/exercicios/$categoriaExercicio'
    | '/dashboard'
    | '/exercicios'
    | '/login'
    | '/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/exercicios/$categoriaExercicio'
    | '/dashboard'
    | '/exercicios'
    | '/login'
    | '/register'
  id:
    | '__root__'
    | '/'
    | '/exercicios/$categoriaExercicio'
    | '/dashboard/'
    | '/exercicios/'
    | '/login/'
    | '/register/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExerciciosCategoriaExercicioRoute: typeof ExerciciosCategoriaExercicioRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  ExerciciosIndexRoute: typeof ExerciciosIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExerciciosCategoriaExercicioRoute: ExerciciosCategoriaExercicioRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  ExerciciosIndexRoute: ExerciciosIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/exercicios/$categoriaExercicio",
        "/dashboard/",
        "/exercicios/",
        "/login/",
        "/register/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/exercicios/$categoriaExercicio": {
      "filePath": "exercicios/$categoriaExercicio.tsx"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx"
    },
    "/exercicios/": {
      "filePath": "exercicios/index.tsx"
    },
    "/login/": {
      "filePath": "login/index.tsx"
    },
    "/register/": {
      "filePath": "register/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
